spring.application.name=backend
# --- MySQL Database Connection ---
spring.datasource.url=jdbc:mysql://localhost:3306/ats_platform_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
# IMPORTANT: Change this to your actual MySQL password (leave blank if you use XAMPP default: spring.datasource.password= )
spring.datasource.password=tiger
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# --- Server Settings ---
server.port=8080